LedgerHQ/app-ethereum

doc/ethapp.asc

Fix formatting

---

src_common/ethUstream.c

Using MIN instead of ternary operator for better code in ethUstream.c.

Minor code improvement

---

Makefile
src/handle_check_address.c
src/handle_check_address.h
src/handle_get_printable_amount.c
src/handle_get_printable_amount.h
src/handle_swap_sign_transaction.c
src/handle_swap_sign_transaction.h
src/main.c
src/swap_lib_calls.h

Backport some of the architectural updates from https://github.com/LedgerHQ/app-xrp/pull/11

Upgrade swap code to better standards

---

Makefile
doc/ethapp_plugins.asc
src/eth_plugin_handler.c
src/eth_plugin_handler.h
src/eth_plugin_interface.h
src/eth_plugin_ui.c
src/main.c
src_common/ethUtils.c
src_common/ethUtils.h
src_features/provideErc20TokenInformation/cmd_provideTokenInfo.c
src_features/setExternalPlugin/cmd_setExternalPlugin.c
src_features/signTx/logic_signTx.c

This will allow plugin to check the address of the tx sender. Useful for some plugins :)

Add pointer to msg_sender in Eth_plugin_finalize

---

CHANGELOG.md

Update changelog file to reflect the changes made in the 1.9.18 version.

Update changelog 1.9.18

---

src/eth_plugin_internal.c
src/eth_plugin_internal.h
src_plugins/compound/compound_plugin.c

Reverts LedgerHQ/app-ethereum#319

Revert "[clean] Removing compound-related plugin code"

---

CHANGELOG.md
Makefile

This PR aimed at fixing the swap from/to ETH variants

fix: allow swap feature on all ETH variants

---

src_bagl/ui_flow_signTx.c
src_bagl/ui_plugin.c
src_bagl/ui_plugin.h
src_common/plugins.c
src_common/plugins.h

Refactorise some common plugin code

commonise plugins

---

src_bagl/ui_flow_stark_sign.c
src_common/starkDisplayUtils.c
src_common/starkDisplayUtils.h

move some stack utility functions to common

move some stack utility functions to common

---

.github/workflows/build-workflow.yml
.github/workflows/ci-workflow.yml

Use the new lite App-Builder to speed-up the CI since the app does not use any Rust.

Switch to using the lite App-Builder container

---

.github/workflows/sdk-generation.yml

[fix] Replace manual commit & push on protected branch with automatic PR with SDK submodule update

---

tests/ragger/conftest.py

Use proper ragger import

---

src_common/network.c

Minor correction of the ticker from EWC to EWT

correcting ticker

---

CHANGELOG.md

Changelog update for last minute fixes

---

.github/workflows/swap-ci-workflow.yml

Added a new workflow that triggers exchange tests

Use reusable workflow for swap tests

---

CHANGELOG.md
Makefile
tests/speculos/test_configuration_cmd.py

Version bump for the next version of the app.

Version bump to 1.10.3-dev

---

src/main.c
src_features/provideDomainName/cmd_provide_domain_name.c
src_nbgl/ui_approve_tx.c
src_nbgl/ui_settings.c
src_nbgl/ui_sign_712.c
src_nbgl/ui_sign_712_v0.c
src_nbgl/ui_sign_message.c
src_nbgl/ui_stark_limit_order.c
src_nbgl/ui_stark_transfer.c

Review fix

---

client/pyproject.toml

[client][fix] Apache License 2.0 has a specific naming for OSI

---

.github/workflows/python-client.yml
client/src/ledger_app_clients/ethereum/client.py
client/src/ledger_app_clients/ethereum/command_builder.py
client/src/ledger_app_clients/ethereum/response_parser.py
client/src/ledger_app_clients/ethereum/utils.py

Fix python-client github job trigger

Fix python-client github job trigger

---

.github/workflows/pr_on_all_plugins.yml

Hotfix workflow name

---

src_nbgl/ui_sign_712.c
src_nbgl/ui_sign_message.c

Stax: Adapt for API LEVEL 14

---

src_nbgl/ui_sign_712.c
src_nbgl/ui_sign_message.c

Fix stax build for API_LEVEL < 14

Fix stax build for API_LEVEL < 14

---

client/README.md

udpate the client README.md file

udpate the client README.md file

---

src/extra_tokens.h
src_features/provideErc20TokenInformation/cmd_provideTokenInfo.c

Discovered by the [app-tester](https://github.com/LedgerHQ/ledger-app-tester).

Fix broken build for chains with extra tokens (testnets)

---

README.md

Fix broken link to developper portal in README.md

Fix broken link to developper portal in README.md

---

ledger_app.toml

Add use cases to manifest

---

src_common/common_utils.c

Report old PR from https://github.com/LedgerHQ/app-ethereum/pull/435

Fix potential oob writes

---

src_nbgl/ui_sign_712_v0.c

Was using the streaming review use case when it did not have to :
* Would show a spinner during the first page transition
* Once on the **Hold to sign** page, would prevent going back to the review

Fix NBGL EIP-712 v0

---

Makefile

Bumped app version.
Changelog will have to be updated for the release of the actual 1.11.0 version.

Bumped app version to 1.10.1-rc1

---

CHANGELOG.md

Add missing feature in changelog for latest release.

Add mentions of transactions from/to fields in changelog

---

Makefile

Version bump to 1.12.0-dev

---

CHANGELOG.md
Makefile

1.11.1 changelog & version number 

---

CHANGELOG.md
Makefile
src/ethUstream.c
src/ethUstream.h
src/network.c
src_features/signMessageEIP712/ui_logic.c
src_features/signTx/cmd_signTx.c

Bring all the changes of the new 1.11.1 app into master. See [changelog](https://github.com/LedgerHQ/app-ethereum/blob/develop/CHANGELOG.md#1111---2024-07-26) for details.

App release 1.11.1

---

client/src/ledger_app_clients/ethereum/settings.py

CI was :red_square:  for Stax because of this.

Revert back to the simpler settings_toggle function in the Python client

---

CHANGELOG.md
Makefile

1.12.0 changelog & version number

---

CHANGELOG.md
Makefile
src_features/signMessage/cmd_signMessage.c

[hotfix] EIP-191 messages regression

---

CHANGELOG.md
Makefile

Bumped app version to 1.13.0-dev

---

CHANGELOG.md
Makefile
src/eth_plugin_handler.c
src/handle_swap_sign_transaction.c
src_features/signTx/cmd_signTx.c
src_features/signTx/logic_signTx.c

[hotfix] Token swap with calldata

---

src_features/signMessageEIP712/field_hash.c

Same as https://github.com/MetaMask/eth-json-rpc-middleware/pull/333

Added hardcoded check to handle Ethermint's EIP-712 messages

---

CHANGELOG.md
Makefile

1.13.0 changelog update & non-dev version number

---

src_nbgl/ui_message_signing.c
src_nbgl/ui_message_signing.h
src_nbgl/ui_sign_712_v0.c

App would not build if full implementation was disabled.

Unlink NBGL implementations of EIP-712 v0 and full

---

src_plugins/erc20/erc20_plugin.c

Renamed "Address" field in ERC-20 approval to "Approve to"

---

client/src/ledger_app_clients/ethereum/client.py
src_bagl/ui_flow_signTx.c
src_features/provideTrustedName/cmd_provide_trusted_name.c
src_features/provideTrustedName/trusted_name.h
src_features/signMessageEIP712/filtering.c
src_features/signMessageEIP712/ui_logic.c
src_features/signMessageEIP712/ui_logic.h
src_nbgl/ui_approve_tx.c
tests/ragger/test_eip712.py

* Fix wrong PKI key usage for trusted names
* Small refactoring of how the app checks against known trusted names

Trusted name misc changes & fixes

---

CHANGELOG.md
Makefile

1.14.0 changelog update & non-dev version number

---

CHANGELOG.md
Makefile

Bumped version to 1.15.0-dev

---

src_plugins/erc20/erc20_plugin.c

Hardcoded list that had not been maintained for years.

Removed hardcoded contract list from ERC-20 internal plugin

---

.github/workflows/cflite_cron.yml

Fix fuzzing workflow syntax warnings

---

src_features/provideDynamicNetwork/network_dynamic.c
tools/gen_dynamic_network.py

Fix Network signing key in tools
Fix parse error code handling

Fix dynamic networks

---

src_features/provideTrustedName/cmd_provide_trusted_name.c

Trusted name cleanup on error

---

src/tlv.c
src/tlv_apdu.c

Fix tlv_from_apdu reset

---

tests/ragger/test_eip712.py
tests/ragger/test_trusted_name.py

Rename 'verbose' fixture which conflict with speculos' one

---

src_features/provide_tx_simulation/cmd_get_tx_simulation.h

Fix W3C strings with null terminator

---

src/eth_plugin_handler.c
src_features/setExternalPlugin/cmd_setExternalPlugin.c
src_features/setPlugin/cmd_setPlugin.c

Fix catch warnings

---

src_nbgl/ui_gcs.c

Made possible by new struct field in SDK.
https://github.com/LedgerHQ/ledger-secure-sdk/pull/900

Fixed contract info NBGL title

---

doc/ethapp.adoc
doc/gcs.md
doc/tlv_structs.md

* Add TLV structs
* Link existing APDU doc to TLV structs
* Add sequence diagram

GCS documentation

---

.github/workflows/codeql_checks.yml

https://github.com/LedgerHQ/ledger-app-builder/pull/173

Switch to the -lite image for CodeQL GH action

---

tests/ragger/test_tx_simulation.py

Explicitely name parameters in sign_tx_common calls (Ragger tests)

---

tests/ragger/test_clone.py

Explicitely name parameters in sign_tx common calls (clone Ragger test)

---

.github/workflows/lint-workflow.yml

https://github.com/LedgerHQ/ledger-app-workflows/pull/118

Now use default version of the reusable lint workflow

---

src_features/provide_trusted_name/trusted_name.c

Comparison never stopped even when it did not make sense to keep going.
Follow-up to #693

Fix version compare in trusted name

---

src_nbgl/ui_gcs.c

The contract address in the contract info disappeared and some titles had to be adjusted.
Introduced in #736

Fix GCS contract info on Nano

---

doc/tlv_structs.md

Added missing TOKEN to ParamType in doc

---

doc/eip712.md
doc/ethapp.adoc

EIP-712 doc

---

.github/workflows/cflite_cron.yml
client/CHANGELOG.md

Prepare client deployment

---

src/list.c
src_features/generic_tx_parser/calldata.c
src_features/generic_tx_parser/gtp_data_path.c
src_features/signMessage/cmd_signMessage.c
src_features/signMessageEIP712/context_712.c
src_features/signMessageEIP712/ui_logic.c
src_nbgl/ui_approve_tx.c

Fix security audit

---

src_features/generic_tx_parser/gtp_tx_info.c

Simple one-line pointer check.

Fix potential crash with generic clear-signing

---

src_features/generic_tx_parser/gtp_data_path.c
src_features/generic_tx_parser/gtp_value.c

Fix GCS regressions

---

CHANGELOG.md
Makefile
src_features/signMessageEIP712/ui_logic.c

App hotfix 1.19.1

---

Makefile

* https://github.com/satoshilabs/slips/blob/master/slip-0044.md
* https://github.com/bitcoin/bips/blob/master/bip-0045.mediawiki

Removed unused derivation paths

---

src/eth_plugin_handler.c
src/plugins/erc1155/erc1155_plugin.c
src/plugins/erc20/erc20_plugin.c
src/plugins/erc721/erc721_plugin.c
src/plugins/eth2/eth2_plugin.c

Cleanup plugin interface
Plugin interface

Cleanup plugin interface
