LedgerHQ/app-ethereum

- CHANGELOG.md
I corrected the Date for 1.6.4 and standardized it to match the date format shown on 1.6.3.
> Standardize Changelog Dates (No Functional Change)

- src/handle_swap_sign_transaction.c
- src/main.c
- src/shared_context.h
- src/ui_flow.c
- src/ui_flow.h
- src_common/ethUstream.c
- src_common/ethUstream.h
- src_features/signTx/logic_signTx.c
- src_features/signTx/ui_flow_signTx.c
This PR aims at adding a special setting to be able to display the nonce when approving a transaction.
The setting is off by default.
Additionally, this PR reworks how the UX_FLOW array was constructed, making it dynamic (this will help if we wish to add additional settings).
> Add setting display nonce

- Makefile
- doc/ethapp.asc
- src/chainConfig.h
- src/eth_plugin_handler.c
- src/main.c
- src/shared_context.h
- src/utils.c
- src/utils.h
- src_common/ethUstream.c
- src_common/ethUstream.h
- src_features/signTx/cmd_signTx.c
- src_features/signTx/logic_signTx.c
- src_features/signTx/ui_common_signTx.c
- src_features/signTx/ui_flow_signTx.c
[EIP 2718](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2718.md) introduces Typed Transaction. Transactions can now have a single byte between 0 and 0x7f to uniquely identify their type.
This PR adapts the txdata parser to support those types of transactions.
It also adds support for EIP2930 which adds a new transaction type (`txtype 01`).
This PR also adds the feature of displaying the ChainID when it's different than 1.
> Support EIP2718 (transaction types) and EIP2930 (access list transactions) and display ChainID

- src/eth_plugin_handler.c
- src/eth_plugin_interface.h
- src/utils.c
- src/utils.h
- src_common/ethUtils.h
This PR adds an interface version to the plugin interface. External plugins can check this interface version, and return an error if they are not compatible with it. This allows to detect discrepancies between the Ethereum app and external plugins.
Additionally, it fixes a few compilation warnings in the Ethereum plugin SDK.
> Security review

- src/eth_plugin_interface.h
- src/eth_plugin_internal.c
- src/eth_plugin_internal.h
- src/utils.c
- src/utils.h
- src_common/ethUtils.c
- src_common/ethUtils.h
- src_common/network.c
- src_common/network.h
- src_features/signTx/logic_signTx.c
- src_plugins/starkware/starkware_plugin.c
- Mark read-only parameters given to plugins as `const`. This is better for both documentation and automated static analysis.
- Define better prototypes for "network" functions. All these functions return `const` objects. `const` qualifiers have been added in the function prototypes that return such objects.
- Change the prototype of `amountToString`. When used "normally", this function always triggers warnings by static analyzers as it takes a `uint8_t` as a size parameter.
It is usually called like this, where `msg->msgLength` is a `uint32_t`:
```c
amountToString(eth_amount, eth_amount_size, WEI_TO_ETHER, "ETH ", msg->msg, msg->msgLength);
```
or like this:
```c
amountToString(eth_amount, eth_amount_size, WEI_TO_ETHER, "ETH ", msg, sizeof(msg));
```
In both cases, a possible truncation …
> Define better prototypes and types

- .github/actions/commit-changes/action.yml
- .github/workflows/sdk-generation.yml
- Makefile
- tools/build_sdk.py
This is linked with [this issue](https://github.com/LedgerHQ/app-plugin-boilerplate/issues/18).
The goal is to generate the SDK used by the plugins automatically, if needed, when merging on `develop` or `master`.
> Automatic generation of the plugin SDK

- .github/actions/commit-changes/action.yml
- .github/workflows/sdk-generation.yml
This PR updates the SDK submodule, and also adds the automatic update of the Ethereum repository when the SDK submodule is automatically updated.
The SDK CI flow when merging on `develop` or `master` should now be:
- Generate the new SDK with `tools/build_sdk.py` (_old behavior_)
- If the SDK changes, creates and pushes a commit **in the SDK repository** with the changes on the related branch (`develop` or `master`) (_old behavior_)
- If the SDK changes, creates and pushes a commit **in the Ethereum repository** with the update SDK submodule on the related branch (`develop` or `master`) (_added by this PR_)
> [add] SDK submodule updated to develop + will now be auto updated

- src/handle_check_address.c
- src/swap_lib_calls.h
- src/utils.c
- src/utils.h
Exchange application can ask for amounts exceeding the buffer size. This PR extends the buffer from 30 to 50 bytes, allowing much bigger transactions.
This PR will need to be synced with the completion of [this PR on exchange](https://github.com/LedgerHQ/app-exchange/pull/41).
> [add] Extending the amount buffer from 30 to 50 bytes

- .github/actions/commit-changes/action.yml
- .github/workflows/sdk-generation.yml
... so that 'develop' SDK commits can be pushed to 'master' when merging.
Current SDK CI does not behave correctly: 
When merging from `develop` to `master`, SDK branch is also `develop`.
The SDK CI tries to update, commit and push the SDK. however, has all modification has been done in `develop`, there is nothing to commit and nothing is pushed or changed. So at the end the `master` of Ethereum points the `develop` branch on its SDK submodule.
We want the pointed branch to be `master`.
This branch remove the previous ambiguous `branch` input of the `commit-changes` custom action, and replaces it with `src_branch` and `dst_branch` inputs. These inputs are not required (in which case the fallback is current branch).
In our case, the `src_branch` is not defined - it is the current branch. …
> [ci][clean] Explicit source and destination branches when auto commit and push

- src_features/signTx/logic_signTx.c
It is possible to write past the `displayBuffer` on `feesToString()` since `displayBufferSize` was not used to check bounds.
> Fix feesToString buffer overflow

- src/eth_plugin_handler.c
Before was not possible to abort the signing process even if the plugin return an error code. According to the docs any return code besides ETH_PLUGIN_RESULT_OK should abort the signing process.
> Abort signing process ETH_PLUGIN_QUERY_*

- src_features/signMessageEIP712/commands_712.c
- src_features/signMessageEIP712/context_712.h
- src_features/signMessageEIP712/path.c
It is possible to send a new structure definition after sending a structure implementation, which makes the app treat unrestricted data as if it was a well defined structure.
This commit tries to fix that behavior. Once a structure implementation is sent, we consider all structures to be defined and we do not allow new definitions
> Eip712 review

- .github/workflows/ci-workflow.yml
- src_bagl/ui_flow_signMessage712.c
- tests/ragger/ethereum_client/client.py
The [dummy UX_STEP](https://github.com/LedgerHQ/app-ethereum/blob/1.10.0/src_bagl/ui_flow_signMessage712.c#L39-L46) was not protected against the user clicking on it.
Over USB HID, this was not really an issue as the APDUs arrive very fast and even spamming the right button would only get the user to the "Approve" screen for a fraction of a second, resulting in a small visual glitch but nothing more.
Over a slow transport like Bluetooth the user would be able to do multiple clicks even at a normal speed, and once on the "Approve" screen clicking left would result in an instant crash of the application/device.
The solution was to entirely disable button clicks on the dummy screen while the app is waiting for more APDUs.
> Fix potential crash with slow APDU transport

- .github/workflows/auto-author-assign.yml
- .github/workflows/build-workflow.yml
- .github/workflows/ci-workflow.yml
- .github/workflows/lint-workflow.yml
- .github/workflows/sdk-generation.yml
Fix the CI deprecation warnings by updating the outdated Github actions :
* checkout
* upload-artifact
* download-artifact
* setup-node
> Update actions to fix deprecation warnings

- .github/actions/commit-changes/action.yml
> [fix] 'github-push-action' does not seem to cope with src:dst git push syntax

- .github/workflows/auto-author-assign.yml
Introduced in #370, the v1 tag does not exist for this action, has to be an explicit full version number.
> Fix PR auto-assign GitHub action

- src/main.c
- src_bagl/ui_flow_signMessage712.c
- src_features/signMessageEIP712/ui_logic.c
- src_features/signMessageEIP712/ui_logic.h
- tests/ragger/eip712/InputData.py
Introduced by the EIP-712 UI split c158c3e5, there was an issue in the EIP712 verbose mode with the "Review struct" screen, it would display it for a fraction of a second then instantly go to the next screen by itself.
The signature process was still working other than this small visual glitch.
It was replying to the last APDU too early, it now properly waits for all the pending "Review struct" screens to be seen by the user before it replies which triggers the next APDU to come in and show the next field.
> EIP-712 verbose mode fix

- src/shared_context.h
...to avoid plugin's 'context->parameterOffset' overflow on large tx
> change dataContext.tokenContext.fieldIndex to uint16_t 

- src_common/network.c
Addition of KCC(KUCOIN Chain) network as ETH clones.
- Homepage:  [https://kcc.io](https://kcc.io)
- Doc: [https://docs.kcc.io](https://docs.kcc.io)
- ChainID: 321
- Chainlist: [https://chainlist.org/chain/321](https://chainlist.org/chain/321)
- KCC
> Add KCC Chain with ChainID = 321 as ETH clones

- CHANGELOG.md
- src/main.c
- src_bagl/ui_flow_signMessage.c
- src_features/signMessage/cmd_signMessage.c
* Just like for EIP-712, there was a weakness with user clicks (https://github.com/LedgerHQ/app-ethereum/pull/364)
* Better APDU error handling when trying to start a new EIP-191 signature in the middle of an already happening one
* Now properly cleans the app context and goes back to the main screen when needed
> Better EIP-191 error handling

- .github/workflows/ci-workflow.yml
- src_bagl/ui_flow_signMessage.c
- tests/speculos/conftest.py
Button clicks were disabled after the event that was supposed to enable them back, instead of before. So the user would be left with an unresponsive app.
Introduced in #402 
Fixed Speculos tests to work with the the latest LNS+ & LNX releases.
Zemu tests are failing since it does not yet support the latest SDKs.
> Fix EIP-191 regression

- src_nbgl/ui_sign_712.c
- src_nbgl/ui_sign_message.c
Replace BAGL_FONT_INTER_REGULAR_32px by BAGL_FONT_INTER_MEDIUM_32px. This change is valid starting from API_LEVEL_9
> Fat: INTER_REGULAR_32 is now INTER_MEDIUM_32

- src_bagl/ui_flow_signTx.c
Introduced by 34ea137c1a1e997580163e3b20ca74ddbb2d9e83
> Fix get_tx_chain_id() implicit declaration warnings

- src_features/signTx/logic_signTx.c
Add a PRINTF of amounts in ERR_SILENT_MODE_CHECK_FAILED
> Add a PRINTF of amounts in ERR_SILENT_MODE_CHECK_FAILED

- src_plugin_sdk/CHANGELOG.md
- src_plugin_sdk/README.md
- src_plugin_sdk/main.c
- tools/build_sdk.py
Missing changes that were not pushed in #475
> Missing plugin SDK changes

- .github/workflows/pr_on_all_plugins.yml
Automatically open PRs on all eth plugins when SDK is updated
> Automatically open PRs on all eth plugins when SDK is updated

- src/eth_plugin_interface.h
- src/eth_plugin_internal.h
> improve plugin interface file

- .github/workflows/pr_on_all_plugins.yml
Add a workaround for Github API refusing to open PRs too quickly
> Add a workaround for Github API refusing to open PRs too quickly

- .github/workflows/pr_on_all_plugins.yml
Increase sleep timer and prevent issue cleanup if matrix fails
> Increase sleep timer and prevent issue cleanup if matrix fails

- src/shared_context.h
Would make transactions with very large (but still within [specs](https://github.com/xinbenlv/EIPs/blob/master/EIPS/eip-2294.md)) chain IDs be refused by the device.
> Fix incorrect assumption on max possible chain ID size

- src/handle_swap_sign_transaction.c
- src/main.c
- src/shared_context.h
- src_features/signTx/logic_signTx.c
Return to Exchange when failing to sign in swap mode instead of wiping context
Align with other coins
> Return to Exchange when failing to sign in swap mode

- Makefile
- src_features/signTx/logic_signTx.c
- src_features/signTx/ui_common_signTx.c
During signature, move parsing and swap fields checking away from main flow
Use standard app crypto helper to simplify io_seproxyhal_touch_tx_ok
> Further reduce stack usage

- src_features/provideErc20TokenInformation/cmd_provideTokenInfo.c
Would refuse a PROVIDE_ERC20_TOKEN_INFORMATION for `crvEURTUSD` even though it is 10 characters long.
> Fix comparison for token ticker length being off by one

- client/README.md
Update installation section of client readme
> Update installation section of client readme

- src/network.c
- src/network.h
- src_features/provideErc20TokenInformation/cmd_provideTokenInfo.c
- src_features/provideNFTInformation/cmd_provideNFTInfo.c
- src_features/setPlugin/cmd_setPlugin.c
Ever since the migration of Ethereum compatible networks into the Ethereum app, some commands were accepted (or refused) when they shouldn't have base on the given chain ID.
> Improve error-handling of chain ID when parsing APDUs

- src_plugin_sdk/CHANGELOG.md
- src_plugin_sdk/standard_plugin.mk
This is causing too many hurdles for too few perks.
standard_plugin.mk: Remove DISABLE_UI
This is causing too many hurdles for too few perks.
> standard_plugin.mk: Remove DISABLE_UI

- client/CHANGELOG.md
- client/src/ledger_app_clients/ethereum/utils.py
Implementation was incorrect and would fail a lot.
> Fix client ecrecover

- makefile_conf/features.mk
- src_features/getEth2PublicKey/cmd_getEth2PublicKey.c
- src_features/getPublicKey/cmd_getPublicKey.c
- src_features/performPrivacyOperation/cmd_performPrivacyOperation.c
- src_features/signMessage/cmd_signMessage.c
- src_features/signMessageEIP712_v0/cmd_signMessage712.c
- src_features/signTx/logic_signTx.c
> Remove useless flag NO_CONSENT

- src/shared_context.h
Bump plugin context size to 10x32
> Bump plugin context size to 10x32

- src_features/signMessageEIP712/commands_712.c
Has always been kind of broken, and can actually cause issues if a filter has been defined for a field inside of an array which turns out to be empty, the app will complain at the very end of the flow that some filters are missing.
This could be improved in the future.
> Remove filters counter check at the end of EIP712 flow

- src/shared_context.h
* Now can store 5 asset information at once (previously 2)
* Update to the [latest plugin SDK](https://github.com/LedgerHQ/ethereum-plugin-sdk/pull/14)
> Increase max assets to 5 + LNS ram optimization

- src/mem.c
- src_bagl/ui_flow_signMessage712.c
- src_features/signMessageEIP712/commands_712.c
- src_features/signMessageEIP712/filtering.c
- src_features/signMessageEIP712/filtering.h
- src_features/signMessageEIP712/path.c
- src_features/signMessageEIP712/path.h
- src_features/signMessageEIP712/ui_logic.c
- src_features/signMessageEIP712/ui_logic.h
Re-activate & fix the EIP-712 filters counter which was disabled in #582, now properly counts unique filters.
The proper handling of filtered path within empty arrays will come later since it also requires a ledgerjs modification.
Uses yet again a bit more RAM (200 bytes) so increased the RAM buffer to make up for it.
Now on Nanos, does not let the user go back to the review page once he has reached the approve/reject.
> EIP-712 filters counter fix + reactivation

- src_nbgl/ui_home.c
The subtext would be too long and make the third setting of the first page overlap with the page footer.
> NBGL settings subtext fix

- CHANGELOG.md
> Fix incorrect year in changelog

- src_features/signMessageEIP712/ui_logic.c
Signing an EIP-712 message would work if done right after opening the app.
Doing it after another transaction or message would fail without even starting the flow on the device.
Introduced in #608
> Fix uninitialized UI buffer for EIP-712

- src_features/signMessageEIP712/path.c
- src_features/signMessageEIP712/path.h
If the app was skipping an empty array that was followed by a non-empty array of structs, the app would not stop at the struct array field but instead at its first non-array child, so its typehash was not computed and the resulting message hash was wrong.
> Fix EIP-712 end of empty arrays traversal

- src/main.c
- src_features/signMessageEIP712/path.c
- src_features/signMessageEIP712/type_hash.c
Non-sensical type definitions could make the EIP-712 `type_hash` function crash.
> Improved EIP-712 error handling

- src/plugins.c
- src/ui_callbacks.h
- src_bagl/common_ui.c
- src_bagl/ui_flow_erc20_approval.c
- src_bagl/ui_flow_getEth2PublicKey.c
- src_bagl/ui_flow_getPublicKey.c
- src_bagl/ui_flow_signMessage.c
- src_bagl/ui_flow_signMessage712.c
- src_bagl/ui_flow_signMessage712_v0.c
- src_bagl/ui_flow_signTx.c
- src_features/getPublicKey/ui_common_getPublicKey.c
- src_features/signMessage/ui_common_signMessage.c
- src_features/signMessageEIP712_common/common_712.c
- src_features/signTx/logic_signTx.c
- src_features/signTx/ui_common_signTx.c
- src_nbgl/ui_approve_tx.c
- src_nbgl/ui_get_eth2_public_key.c
- src_nbgl/ui_get_public_key.c
- src_nbgl/ui_message_signing.c
- src_nbgl/ui_sign_message.c
Send the result immediately rather than waiting for the end of the notification.
This fix #637
> B2CA-1776: Change Confirm/Cancel notifications order

- glyphs/chain_943_64px.gif
- src/network.c
Please provide a detailed description of what was done in this PR.
Support for PulseChain was missed during updates earlier this year. I've added it back following the new patterns.
Ledger Live integration: https://github.com/LedgerHQ/ledger-live/pull/7607
> Add and update PulseChain Networks

- src/common_ui.h
- src_bagl/ui_flow.h
- src_bagl/ui_flow_signMessage712.c
- src_features/signMessageEIP712/commands_712.c
- src_features/signMessageEIP712/context_712.c
- src_features/signMessageEIP712/context_712.h
- src_features/signMessageEIP712/ui_logic.c
- src_features/signMessageEIP712/ui_logic.h
- src_features/signTx/logic_signTx.c
- src_nbgl/ui_approve_tx.c
- src_nbgl/ui_blind_signing.c
- src_nbgl/ui_message_signing.h
- src_nbgl/ui_sign_712.c
- tests/ragger/test_eip712.py
Please provide a detailed description of what was done in this PR.
> B2CA-1619: Blind Signing friction

- src_features/signMessageEIP712/commands_712.c
- src_features/signMessageEIP712/ui_logic.c
- src_features/signMessageEIP712/ui_logic.h
- src_nbgl/ui_sign_712.c
- tests/ragger/test_eip712.py
Changes default behavior for unfiltered EIP-712 reviews for Flex & Stax, adds a skip button.
> Unfiltered EIP-712 fallback to raw message for NBGL devices + skip button

- src_features/provideTrustedName/cmd_provide_trusted_name.c
> Trusted names security fixes

- src_features/signMessageEIP712/commands_712.c
- src_features/signMessageEIP712/filtering.c
- src_features/signMessageEIP712/filtering.h
- src_features/signMessageEIP712/path.c
- src_features/signMessageEIP712/path.h
- src_features/signMessageEIP712/ui_logic.c
- src_features/signMessageEIP712/ui_logic.h
For discarded filters, the path CRC was computed on the regular path instead of the backed-up path, so the app could find an already existing CRC in memory when the filter was actually unique.
> Fix EIP-712 discarded filters

- CHANGELOG.md
- makefile_conf/chain/ethereum_classic.mk
Introduced in #634, Ledger Live uses the clone on both paths (44'/60' & 44'/61').
Might be removed again in the future if Live changes this behaviour.
> [hotfix] ETC with ETH derivation path

- src/shared_context.h
- src_plugins/erc20/erc20_plugin.c
- src_plugins/eth2/eth2_plugin.c
* Fix amount buffer being not big enough to accommodate a ticker if the amount is already the largest possible
* Fix two calls to `amountToString` having a hardcoded (and wrong) output buffer size
> Fix amount formatting

- client/src/ledger_app_clients/ethereum/command_builder.py
- src/ethUstream.c
- src/ledger_pki.c
- src/mem.c
- src/network.c
- src/network.h
- src/public_keys.h
- src_features/provideNFTInformation/cmd_provideNFTInfo.c
- src_features/signMessageEIP712/ui_logic.c
- src_features/signTx/cmd_signTx.c
* When the app hadn't received a dynamic network it could theoretically find a match for chain ID 0 (since the slots are initialized with 0)
* Removed redundant pin-check in the sign function
* Fix for the long-standing https://github.com/LedgerHQ/app-ethereum/issues/409
* Removed the provide NFT info APDU requiring the internal NFT "plugin" to be loaded
> Various QoL changes & small fixes

- src_features/provideDynamicNetwork/network_dynamic.c
Fix issue identified in security review.
> Fix potential out-of-bounds read by up to 2 bytes during TLV parsing

- src_features/provideTrustedName/cmd_provide_trusted_name.c
- tests/ragger/conftest.py
- tests/ragger/test_trusted_name.py
The version comparison loop was, for some reason, looping only as long as each element of the version numbers were the same.
Removed that condition and switched to a simpler `for () {}` loop.
> Fix trusted name expiration check

- src_features/provideDynamicNetwork/network_dynamic.c
- src_features/provideTrustedName/cmd_provide_trusted_name.c
Make all the existing features using TLV use the new parser that came with the generic parser.
> Unify TLV parsing

- src/mem.c
- src/mem.h
- src/mem_utils.c
- src/mem_utils.h
- src_features/generic_tx_parser/calldata.c
- src_features/generic_tx_parser/cmd_tx_info.c
- src_features/generic_tx_parser/gtp_data_path.c
- src_features/generic_tx_parser/gtp_data_path.h
- src_features/generic_tx_parser/gtp_param_amount.c
- src_features/generic_tx_parser/gtp_param_datetime.c
- src_features/generic_tx_parser/gtp_param_duration.c
- src_features/generic_tx_parser/gtp_param_enum.c
- src_features/generic_tx_parser/gtp_param_nft.c
- src_features/generic_tx_parser/gtp_param_raw.c
- src_features/generic_tx_parser/gtp_param_token_amount.c
- src_features/generic_tx_parser/gtp_param_trusted_name.c
- src_features/generic_tx_parser/gtp_param_unit.c
- src_features/generic_tx_parser/gtp_parsed_value.h
- src_features/generic_tx_parser/gtp_value.c
- src_features/generic_tx_parser/gtp_value.h
Simple compression of the stored calldata in RAM during generic clear-signing.
> calldata compression

- tests/fuzzing/CMakeLists.txt
`explicit_bzero` isn't counted as initializing a variable for the fuzzer.
> Fix for fuzzing false positive with unitialized variables

- client/src/ledger_app_clients/ethereum/gcs.py
runtime crash as this type annotation is not backward compatible for python before 3.10
> ledger_app_clients.ethereum: fix type checking annotation for python

- src_features/signTx/logic_signTx.c
Return invalid data status unless return is okay.
Handle finalize error if return code is an error result code, not only zero.
> eth,plugin: improve plugin finalize error checks

- client/src/ledger_app_clients/ethereum/eip712/struct.py
- tests/ragger/test_eip712.py
* One syntax error that Python 3.10 was permissive to
* One actual change of Python 3.11 around the handling of `Enum` types
> Fix compatibility with Python 3.11

- client/src/ledger_app_clients/ethereum/command_builder.py
- doc/ethapp.adoc
- src/network.c
- src_features/provide_network_info/cmd_network_info.c
- src_features/provide_network_info/network_info.c
* Now the TLV payload is size prefixed, so if it ever grows bigger than the max size of an APDU, the APDU format will remain unchanged
* Now supports receiving the same network multiple times (was an issue when running the Ragger tests on device)
* Now the network info slot if left unchanged if the given network info is invalid
> Improve network info support

- tests/ragger/test_gcs.py
> Explicit named mode parameter in sign function calls in GCS Ragger tests

- doc/ethapp.adoc
Clarify that `GET ETH PUBLIC ADDRESS` APDU request returns ASCII-encoded address
> docs: Clarify address format in APDU docs

- src_features/generic_tx_parser/gtp_param_datetime.c
- src_features/signMessageEIP712/ui_logic.c
> Now handles unlimited datetimes

- src_features/generic_tx_parser/cmd_field.c
- src_features/generic_tx_parser/cmd_tx_info.c
- src_features/provide_proxy_info/cmd_proxy_info.c
- src_features/provide_trusted_name/cmd_trusted_name.c
Could be ween with incorrect TLV structs.
> Fix potential memory leak with incorrect TLV structs

- client/pyproject.toml
- client/src/ledger_app_clients/ethereum/client.py
- client/src/ledger_app_clients/ethereum/response_parser.py
- client/src/ledger_app_clients/ethereum/utils.py
- tests/ragger/requirements.txt
- tests/ragger/test_eip7702.py
- tests/ragger/test_sign.py
EIP-7702 tests benefit greatly from this newer Web3.py version.
> Update client to use Web3.py v7

- src_features/provide_tx_simulation/cmd_get_tx_simulation.c
- src_features/provide_tx_simulation/cmd_get_tx_simulation.h
- src_nbgl/ui_sign_712.c
- src_nbgl/ui_sign_message.c
Update Transaction Check error case for streaming mode (for the moment, EIP712)
If the payloadd is not received, do not show the final warning message.
> Hotfix tx check eip712

- CHANGELOG.md
- Makefile
> Version bump

- src/tlv_apdu.c
On long (across multiple APDUs) payloads.
> Fix potential double dealloc with tlv_from_apdu

- src_features/generic_tx_parser/calldata.c
> Fix calldata_get_chunk bug

- tests/fuzzing/CMakeLists.txt
- tests/fuzzing/src/fuzzer.c
- tests/fuzzing/src/mock.c
This PR adds a fuzzing harness for the EIP7702 APDU.
> Add eip7702 fuzzer

- src/list.c
- src/list.h
- src/mem.c
- src/mem.h
- src/mem_utils.c
- src/mem_utils.h
- src_features/signMessageEIP712/commands_712.c
- src_features/signMessageEIP712/context_712.c
- src_features/signMessageEIP712/encode_field.c
- src_features/signMessageEIP712/encode_field.h
- src_features/signMessageEIP712/field_hash.c
- src_features/signMessageEIP712/filtering.c
- src_features/signMessageEIP712/format_hash_field_type.c
- src_features/signMessageEIP712/format_hash_field_type.h
- src_features/signMessageEIP712/path.c
- src_features/signMessageEIP712/path.h
- src_features/signMessageEIP712/schema_hash.c
- src_features/signMessageEIP712/sol_typenames.c
- src_features/signMessageEIP712/sol_typenames.h
- src_features/signMessageEIP712/type_hash.c
- src_features/signMessageEIP712/type_hash.h
- src_features/signMessageEIP712/typed_data.c
- src_features/signMessageEIP712/typed_data.h
- src_features/signMessageEIP712/ui_logic.c
- src_features/signMessageEIP712/ui_logic.h
- src_nbgl/ui_gcs.c
- src_nbgl/ui_sign_712.c
- tools/valground.py
> EIP-712 memory allocator migration

- .github/workflows/build_and_functional_tests.yml
- src/mem.c
- src/mem.h
- src/mem_utils.c
- src/mem_utils.h
- src_features/provide_network_info/cmd_network_info.c
- src_features/provide_network_info/network_info.c
- src_features/provide_trusted_name/trusted_name.c
- src_features/provide_trusted_name/trusted_name.h
- src_features/signTx/cmd_signTx.c
- src_nbgl/ui_gcs.c
- src_nbgl/ui_message_signing.c
- tools/valground.py
- Add logic to track missing allocation/free utility functions
- Fix few remaining memory leaks
- And adapt `valground` script
- Add `-q/--quiet` option to limit the logs (hence, only print the memory leaks)
- Add a the global Higer Max Overtime, corresponding to the max needed allocated memory over all run tests
- Add workflow test (based on ragger) to check the memory leaks
> Improve memory management
